### ISSUE TITLE
Does not seem to work on 11.0.0-preview6

### ISSUE THREAD

**Issue by IhateTrains** [AvaloniaCommunity/MessageBox.Avalonia#129]
```
System.MissingFieldException: Field not found: 'Avalonia.Controls.Window.WindowStartupLocationProperty'.
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulate(IServiceProvider, MsBoxCustomWindow)
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulateTrampoline(MsBoxCustomWindow)
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   ```

**Comment by aldelaro5** [comment]
Hey, I actually am aware of what is happening on this one, but I only experienced it on nightly build before so I waited for them to release it to investigate.

Basically, the issue is with markdown.avalonia: this error comes from their scrollviewer crashing. I wanted to help that project upgrade to preview 6, but unfortunately, its project has a build dependancy on AvaloniaEdit.

So I tried to upgrade that, but unfortunately, an unexpected perf issue happened. I still made a WIP pr, but you can see the details here: https://github.com/AvaloniaUI/AvaloniaEdit/pull/318

Essentially, this is blocked by markdown.avalonia upgrading to preview6...

...which is blocked by avaloniaedit upgrading to preview 6.

It's a dependency upgrade fun!

**Comment by aldelaro5** [comment]
oh Interesting, I was hitting build issues with their demo projects so I wonder if those are still broken, maybe it didn't affect the lib.

Well my perf issue on avalonia edit is still valid, but basically, it's still blocked by it in the sense we need to wait they release the a10 version on nuget and then have messagebox.avalonia upgrade to it.

**Comment by ProbablePrime** [comment]
I'm not certain how the two are related, I don't see Avalonia Edit within this repo's dependencies. Is this because you use it for development? I just use regular visual studio and haven't come across any issues, in poking at the source code of this library.

**Comment by aldelaro5** [comment]
The demo project uses it, you can see they left its version to preview 5 in the directory.build.props which I find interesting because when I tried it, it wouldn't build, but maybe my rider was missbehaving and I didn't see it.

**Comment by ProbablePrime** [comment]
Ahh, I see ok. Maybe I'll take a deeper loop.
