### ISSUE TITLE
Why is the main window still closed?

### ISSUE THREAD

**Issue by alabohai** [AvaloniaCommunity/MessageBox.Avalonia#178]
I want a confirmation window to pop up when I click the close button in the upper right corner of the application. If I click the "yes" button, the application will be closed. If I click the "no" button, the application will not be closed. How can I achieve this?

I tried to implement it through the following code, but when I clicked the "No" button, the application was still closed. Why?

public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        this.DataContext = new MainViewModel();
    }

    private async void Window_Closing(object sender, WindowClosingEventArgs e)
    {
           var result = await MsBox.Avalonia.MessageBoxManager.GetMessageBoxStandard("Quit?", "Are you sure you want to exit the application?",  ButtonEnum.YesNo, MsBox.Avalonia.Enums.Icon.Question).ShowAsync();
            if (result.Equals(ButtonResult.No))
            {
                e.Cancel = true;
                return;
            }
    }
}

I stepped into debugging the code and found that this line of code (e.Cancel = true; ) was executed. Why is the main window still closed?

**Comment by CreateLab** [comment]
You should handle window close event for doing as u wanna

**Comment by shelbysk92** [comment]
This took me a while to solve, and in my opinion the solution is messy.

First, the reason the window closes immediately is because the Window_Closing method is declared as async, and you are calling ```await ...ShowAsync()```.  In an async method, when it hits the "await" line, it starts the ShowAsync call asynchronously, then immediately exits the method so it can continue with other tasks.  Normally, once an awaited task is complete, it then returns control to the method on the line immediately after the ShowAsync call (where you check the result and set e.Cancel to true). Since the method is Window_Closing, exiting that function will close the window.  It skipped the ```e.Cancel = true``` because it's still waiting for you to answer the dialog, but has already closed the window.

Now, this should have been simple to fix, I could just change it to ```var result = ShowAsync().Result;```, effectively making it into a synchronous call that waits for the response to the dialog.  In this case, it didn't work for the dialog, it froze up the application (some sort of thread contention).  I then tried ```Task.Run(ShowAsync).Result``` and this resulted it an exception "Call from an invalid thread".  My research let me to change the call to ```var result = Dispatcher.UIThread.InvokeAsync(dialog.ShowAsync).Result;```.  This changed the call to be on the UI thread, which prevented the exception, but then froze the application completely.

My convoluted solution works, as follows.  First,  I added a bool property to the page, called OverrideClose, defaulted to false.  In my OnClosing method.  I also set ```e.Cancel = true``` unless OverrideClose is true.  Then I called another async method I added called ```CloseApp()```, which just calls a simple ```var result = await dialog.ShowAsync();```, sets OverrideClose to true, and then manually calls ```Close();```.  The reason I needed the OverrideClose was that without it, the manual Close call would trigger OnClosing again and result in an infinitely loop of close/onclosing.

So... after all that, this works.  The dialog appears, the window doesn't close unless the user selects the correct dialog option, and no more exceptions and freezes.  Note that I am calling CloseApp() without await, even though it's declared async; that would result in the same original problem.  CloseApp has to be declared async though, since I need to call await ```dialog.ShowAsync()```.
```
private async void CloseApp()
{
// .... I define my dialog  before this
    var result = await dialog.ShowAsync();
    if (result == "No")
        return;
    OverrideClose = true;
    Close();
}

protected override void OnClosing(WindowClosingEventArgs e)
{
    base.OnClosing(e);
    if (OverrideClose)
    {
        OverrideClose = false;
        return;
    }
    e.Cancel = true;
    CloseApp();
}
```
